### PR TITLE
Make STARTTLS LDAP option more precise on UI

### LINKED ISSUE #129: Make STARTTLS LDAP option more precise on UI
Currently, the checkbox "Use TLS" enables STARTTLS:

https://github.com/uhm-coe/authorizer/blob/05bcdc6921478154232240fb52a464a34f172cd1/src/authorizer/options/external/class-ldap.php#L104

If the user specifies an `ldaps://` connection, the checkbox has no effect:

https://github.com/uhm-coe/authorizer/blob/05bcdc6921478154232240fb52a464a34f172cd1/src/authorizer/class-authentication.php#L1105

In my opinion, the UI is not quite clear regarding these things. I would therefore propose the following changes:

* Replace "Use TLS" with "Use STARTTLS" (because TLS is also used in an `ldaps://` connection)
* Replace "If ldaps is used, this should be unchecked" with "If ldaps is used, this has no effect" (to be more explicit)

If you want, I can try to open a PR with these particular changes.

### PR DESCRIPTION
**Pull request by TuringTux**
Closes #129.

This also attempts to provide Spanish and French translations, however, they should ideally be reviewed by someone with better knowledge of those languages.

### CODE REVIEW

**Comment by TuringTux** [comment]
I have manually changed the string in the `.php` file and in one translation file (`authorizer.pot`), however, that translation file seems to be automatically generated, so I probably need to try doing this with POedit.

**Comment by figureone** [comment]
This looks great, thanks so much! It will be included in the next release

**Comment by figureone** [comment]
Re: Poedit, I'm running a pretty old version myself and I think a lot of the formatting of the `.pot` output has changed between versions. Thanks for trimming that down to just the relevant changes, makes the code review easier!

**Comment by TuringTux** [comment]
Thank you for merging!

Yes, that is also what I suspected. I apologize for the bigger Spanish and French translation files, they are not trimmed to the max, because I had to update them from the `.pot` file and then somewhat lost track over the changes.

**Comment by figureone** [comment]
Aloha, version 3.6.3 has now been released. Thanks so much for your contribution!

**Comment by TuringTux** [comment]
That's very nice, thank you! I've just checked it and our production WordPress instance has already updated to the latest version, looks very nice indeed :)

**Pull request merged**
