### PR TITLE
Simple History Log: Use different message if global lockout is triggered

### LINKED ISSUE #141: Adjust message logged to Simple History about global lockout
Currently, Authorizer maintains not only a per-user failed login counter, but also a global failed login counter for all attempts to log in as users that don't exist[^1][^2].

Whenever the global lockout is triggered, a message like this is logged to Simple History:

> Authorizer lockout triggered for 10 minutes on user wwwadmin after the 104th invalid attempt.

However, this doesn't actually mean someone tried 104 passwords on `wwwadmin`, but just that someone tried 104 passwords on several users, all non-existing. I think the message could be reworded to make this more clear, e.g.:

> Authorizer lockout triggered for 10 minutes on all non-existent usernames after the 104th invalid attempt (latest non-existent username: `wwwadmin`).

The reworded message could help in debugging tricky issues like #138.

[^1]: The reason for this is [documented](https://github.com/uhm-coe/authorizer/blob/eb085e120618bb26e2cea817a0a0a623e7cdcf55/src/authorizer/class-login-form.php#L332): If the plugin locked only existing user names, an attacker can find out if a user with a certain name exists by bombarding the page with invalid password attempts for that user. If the user gets locked, the attacker would have confirmed the user exists. Therefore, the plugin also counts login attempts for non-existent usernames. 

[^2]: Furthermore, it also makes the plugin more robust and able to deal with complexities like these: https://github.com/uhm-coe/authorizer/issues/138#issuecomment-1930933507

### PR DESCRIPTION
**Pull request by TuringTux**
Closes #141.

### CODE REVIEW

**Comment by TuringTux** [comment]
I have not yet provided translations for this, because I can't recall how exactly adding them worked. If requested, I can add them.

**Comment by figureone** [comment]
Looks great! We're trying to get a new version soon out so this will be bundled in. Cheers!

**Comment by figureone** [comment]
For translations I have been using Poedit to update the translation files (looks like my copy is crashing on me so I'll have to work on that). Don't worry about that unless you want to go down the rabbit hole :)

**Comment by TuringTux** [comment]
Great, thanks! And thanks for updating the translation files for me :)

**Comment by figureone** [comment]
Added new translatable string here: https://github.com/uhm-coe/authorizer/commit/264df4164b597a11889e4d2b5fff785925622d27

And for the `es` and `fr` translations: https://github.com/uhm-coe/authorizer/commit/90eef8eb82264d85c45d5e275f3dfad80ddafa6b
@julienlusson has provided excellent French translations in the past so let us know if you have time to update this one!

Thanks all, cheers

**Comment by figureone** [comment]
You're the best @julienlusson thanks!
https://github.com/uhm-coe/authorizer/pull/145

**Pull request merged**
